### ISSUE TITLE
dummyproject demo run problem

### ISSUE THREAD

**Issue by pampanelson** [adamrehn/pixel-streaming-linux#10]
I use the dummy project from https://github.com/adamrehn/ue4-example-dockerfiles

here is  result of  command :  docker run --gpus all -e DISPLAY -v ${HOME}/.Xauthority:/home/user/.Xauthority -v /tmp/.X11-unix:/tmp/.X11-unix --rm -it --network="ue4"

ue4@03117eed1bd5:/$ /home/ue4/project/DummyProject.sh -AudioMixer -opengl4
4.23.1-8386587+++UE4+Release-4.23 517 0
Disabling core dumps.
sh: 1: xdg-user-dir: not found
error: XDG_RUNTIME_DIR not set in the environment.
Unable to read VR Path Registry from /home/ue4/.config/openvr/openvrpaths.vrpath
Unable to read VR Path Registry from /home/ue4/.config/openvr/openvrpaths.vrpath
Checking Pak Config

by nvidia-smi  output :
|   0  GeForce GT 730M     Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   67C    P0    N/A /  N/A |    868MiB /   983MiB |     N/A      Default
there is usage of gpu by the ue4 dummy project 

and the top output says so:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
18354 pata      20   0 21.674g 454784 220932 S 109.3  5.8   3:53.50 DummyProject-Li
31323 pata      20   0  373892   8004   3024 R  99.7  0.1  19:19.23 WebRTCProxy

but open 127.0.0.1 , the Show Stats info is Not connected

projec , proxy and server run in seperate containers with same parameter --network="ue4" 

finaly, thanks for the great work!!

**Comment by pampanelson** [comment]
and I'm just aware of my testing gpu is not in the list of gpus which supporting nvenc  https://developer.nvidia.com/video-encode-decode-gpu-support-matrix
it's the problem about ?

**Comment by adamrehn** [comment]
The output there shows that you've packaged your project in Shipping configuration, which means you don't get enough log output to actually diagnose problems. You'll need to package in Development configuration so you can get some meaningful log output.

**Comment by MrZivChu** [comment]
@pampanelson 
Hello, friend, have you solved your problem? Can you share the solution？Thank you

**Comment by joelelrocker** [comment]
Hi folks @MrZivChu @pampanelson , I bet you guys figured this out already but I was running into the same problem and was able to get this up and running. The fix was actually quite simple. I tried over and over again on my desktop to connect and continually had the same error/behavior... I believe that this is a Firefox issue. I ran the WebRTCProxy, server, and game from my desktop (centos 7 using firefox) and used my laptop ( windows 10 using google chrome) to connect. It is working great. I'm going to install chrome on my desktop and see it it runs then move all this into k8's. I'll be happy to share my yaml's once i'm done. EDIT: installed chrome on my centos desktop and it works great as well.
