### ISSUE TITLE
LogLoad: LoadMaChecking Pak Config  get stuck

### ISSUE THREAD

**Issue by Jggggg** [adamrehn/pixel-streaming-linux#18]
@adamrehn hi，adamrehn，
The address of the project that I use is https://github.com/adamrehn/ue4-example-dockerfiles/tree/master/pixel-streaming/4.23
According to this document [https://adamrehn.com/articles/pixel-streaming-in-linux-containers/#building-container-images](url)
I configured the environment
But I met one problem:
![Screenshot from 2020-08-28 16-26-37](https://user-images.githubusercontent.com/19992969/91540396-52418280-e94d-11ea-9843-73cc3237aba5.png)
![Screenshot from 2020-08-28 16-26-40](https://user-images.githubusercontent.com/19992969/91540447-64232580-e94d-11ea-84c9-427c303eb6ad.png)
![Screenshot from 2020-08-28 16-26-42](https://user-images.githubusercontent.com/19992969/91540455-671e1600-e94d-11ea-87e5-b45f39ad33ee.png)
![Screenshot from 2020-08-28 16-26-50](https://user-images.githubusercontent.com/19992969/91540474-700ee780-e94d-11ea-8e42-18292344c98b.png)
![Screenshot from 2020-08-28 16-26-53](https://user-images.githubusercontent.com/19992969/91540491-74d39b80-e94d-11ea-9d2c-e7d735a19be3.png)
[log.txt](https://github.com/adamrehn/pixel-streaming-linux/files/5141016/log.txt)

Look forward to your reply，Thank you

**Comment by xxjunxx** [comment]
I got stuck at "Checking Pak Config" running the runtime image. What command are you using to run the runtime image? `docker run --gpus all --rm --name run --network=host  xj/run`

**Comment by adamrehn** [comment]
Apologies for the delay in responding to this issue, I've been drowning in work over the past few months and progress on addressing my GitHub backlog has been frustratingly slow.

In multiple screenshots there I can see that you are specifying the Docker flag `--network=host` **after** the container image name, rather than **before** it. This will pass that as an argument to the entrypoint inside the container (which will then be ignored since it has no meaning to the Unreal Engine or its Pixel Streaming servers), rather than being recognised as a flag instructing Docker itself to use host networking mode. Correcting the placement of the flag should trigger the expected behaviour whereby all three containers are able to communicate via the host's network interface.
