### ISSUE TITLE
Enabled "Pixel Streaming" plugin leads to build failure

### ISSUE THREAD

**Issue by amesgames** [adamrehn/pixel-streaming-linux#3]
Hi, Adam.

I am trying to walk through these instructions: https://adamrehn.com/articles/pixel-streaming-in-linux-containers/#where-to-get-the-code-and-file-issues.

I have been able to build images from the _4.23.1-pixelstreaming_ branch of your fork.

I assumed that I needed to enable the "Pixel Streaming" plugin in my test UE4 project before building my runtime image using a Dockerfile very much like the one in those instructions.

However, with "Pixel Streaming" plugin enabled, I get a build exception thrown when running _ue4 package_.

<pre>
Running: mono "/home/ue4/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe" PixelStreamingEditor Linux Development -Project=/tmp/project/PixelStreaming.uproject  /tmp/project/PixelStreaming.uproject -NoUBTMakefiles  -Manifest=/tmp/project/Intermediate/Build/Manifest.xml -NoHotReload -log="/home/ue4/Library/Logs/Unreal Engine/LocalBuildLogs/UBT-PixelStreamingEditor-Linux-Development.txt"
  ERROR: Plugin 'PixelStreaming' (referenced via PixelStreaming.uproject) does not contain the 'PixelStreaming' module, but lists it in '/home/ue4/UnrealEngine/Engine/Plugins/Experimental/PixelStreaming/PixelStreaming.uplugin'.
</pre>

The UE4 test project I am using is simply the top-down template with Pixel Streaming plugin enabled.

Is there a test project you have that I can use to test and understand the workflow?

**Comment by amesgames** [comment]
I just discovered this older project: https://github.com/adamrehn/ue4-cloud-rendering-demo

Is that a good place to start? I noticed it has the UE4Capture plugin inside the project folder.

**Comment by adamrehn** [comment]
The old [ue4-cloud-rendering-demo](https://github.com/adamrehn/ue4-cloud-rendering-demo) project is designed for use with my [UE4Capture plugin](https://github.com/adamrehn/UE4Capture), which served as a proof-of-concept cross-platform alternative to Pixel Streaming prior to my subsequent work enabling Linux support for Pixel Streaming itself. The recommended demo project for testing Pixel Streaming for Linux is [Epic's official Pixel Streaming Demo](https://docs.unrealengine.com/en-US/Resources/Showcases/PixelStreamingShowcase/index.html), but any project that enables the `PixelStreaming` plugin should work fine.

I've been unable to reproduce the error you encountered when packaging either the official Pixel Streaming Demo or a minimal test project using a freshly-built `adamrehn/ue4-full:4.23.1-pixelstreaming` image, which was created using [the command listed in the Linux Pixel Streaming article](https://adamrehn.com/articles/pixel-streaming-in-linux-containers/#building-container-images). A quick test with an unmodified build of Unreal Engine 4.23.1 confirms that the error does not occur if you've accidentally built the vanilla version of 4.23.1 instead of my Pixel Streaming fork (since the `PixelStreaming` plugin is simply ignored due to being incompatible with Linux), which leaves me at a bit of a loss as to what's causing it. What command did you use to build your container image?

**Comment by adamrehn** [comment]
Nevermind, I've managed to figure it out. On a hunch, I created a test project called `PixelStreaming` and was able to reproduce the error when attempting to package it. Evidently the duplicate module name `PixelStreaming` in both the project and the Pixel Streaming plugin is confusing UnrealBuildTool, leading to that error. Everything should work fine if you name your project something else.
