### ISSUE TITLE
Vulkan drivers fail on AWS T4

### ISSUE THREAD

**Issue by lukehb** [adamrehn/pixel-streaming-linux#30]
I am porting this issue from our old issue tracker for @lcdlv

```
I had a VM in AWS with a T4, but I had problems with Vulkan drivers... Im stuck!
```

**Comment by lukehb** [comment]
For AWS with the T4, a few questions:

- Do you have log output you can share?
- What base AMI did you use?
- Did you install the Nvidia drivers as per [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html)?

My goal is to determine if this an issue with our Pixel Streaming for Linux implementation or an AWS-specific configuration issue, so any more info in that direction would be helpful.

**Comment by lcdlv** [comment]
Hi Again!!! A lot of comments to do about it:

I installed CUDA Toolkit, also I installed drivers from AWS docs too (I tried Gaming and GRID, with the same result).
"Vulkaninfo" works in Ubuntu 18.04 and FAIL in Ubuntu 20.04 (/build/vulkan-tools-KEbD_A/vulkan-tools-1.2.131.1+dfsg1/vulkaninfo/vulkaninfo.h:939: failed with ERROR_INITIALIZATION_FAILED).
The problem with Ubuntu 18.04 is the Vulkan drivers seem to be old, and if I start the engine changing BaseEngine.ini to OpenGL never start, because my openGL is 3.1 and I couldn't find a way to update to 3.2... The mesa drivers are old or something, and the last OpenGL is 3.1 for 18.04.
In 20.04 I update to OpenGL 3.2 and the engine starts with OpenGL, but if I change to start with Vulkan fails.

After start the engine in 20.04 with OpenGL I try to open Pixel Streming Demo project... crash!!! Here is the LOG:

**UPDATE: Only happen when Pixel Streaming Plugin is enabled, or CUDA plugin is enabled.**

LoginId:ec2274b514a32d6088e82472142da370-000003e8
EpicAccountId:

Caught signal

libUE4Editor-CUDA.so!FCUDAModule::InitCuda() [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Plugins/CUDA/Source/Private/CudaModule.cpp:36]
libUE4Editor-CUDA.so!TBaseRawMethodDelegateInstance<false, FCUDAModule, void ()>::ExecuteIfSafe() const [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Source/Runtime/Core/Public/Delegates/DelegateInstancesImpl.h:544]
UE4Editor!TBaseMulticastDelegate<void>::Broadcast() const [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Source/Runtime/Core/Public/Delegates/DelegateSignatureImpl.inl:1013]
UE4Editor!FEngineLoop::Init() [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:3998]
libUE4Editor-UnrealEd.so!EditorInit(IEngineLoop&) [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Source/Editor/UnrealEd/Private/UnrealEdGlobals.cpp:92]
UE4Editor!GuardedMain(char16_t const*) [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Source/Runtime/Launch/Private/Launch.cpp:148]
libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/home/ubuntu/Desktop/UnrealEngine-4.25-pixelstreaming/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
libc.so.6!__libc_start_main(+0xf2)
UE4Editor!_start()

I had a Warning compiling the engine, at ./GenerateProjectFiles.sh. This is the error:

"WARNING: Library 'cudart_static' was not resolvable to a file when used in Module 'CUDA', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning."

UPDATE: I re-installed CUDA toolkit again, in case if not well installed, and re-run the engine source compile. I was thinking "maybe this CUDA error will be solved" but it's happen again.

I downloaded CUDA Toolkit from NVIDIA page, using the installer:

wget https://developer.download.nvidia.com/compute/cuda/11.2.1/local_installers/cuda_11.2.1_460.32.03_linux.run
sudo sh cuda_11.2.1_460.32.03_linux.run

https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=runfilelocal

AMI: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20201026

Thanks guys in advance.

**Comment by ImmortalEmperor** [comment]
Hi @lcdlv that warning about cudart_static should not actually kill the build its just saying that UBT is having to look system wide for the library and might be a bit slower. If CUDA actually cannot be found it would a) fail the build saying the path does not exist or b) you would get linker errors at the end of the build. 

The crash is occuring on line 36 in CUDA module which is a Vulkan call to get the running device.  Pixel streaming with 4.25 *will not work with OpenGL* as Epic has deprecated a lot of stuff with the RHI making it not worthwhile. It sounds like your AMI is not properly configured with Vulkan could you go through your configuration?

**Comment by lcdlv** [comment]
tell me what information you need and I do that and sent to you.

**Comment by lukehb** [comment]
Would you please run `nvidia-smi` and share the output here.

Regarding Ubuntu 18.04/20.04, we would expect both versions to work if they have the latest NVIDIA drivers and CUDA installed. If you want, you could try using an AMI with CUDA already installed, such as [this one](https://aws.amazon.com/marketplace/pp/B076K31M1S?qid=1613538553921&sr=0-7&ref_=srh_res_product_title).

**Comment by lcdlv** [comment]
Ok, working with a real Notebook with a RTX 2060 everything works "like tonight"!
I will try the AMI you said and then I tell you how that works.
Now I have other problems, but I will open a new Issue haha. Thanks!

**Comment by lukehb** [comment]
@lcdlv Based on #33, it would be interesting to know if your AWS version now runs if you package for `Development`?

**Comment by lcdlv** [comment]
Yes, in development works, in Shipping not work.

**Comment by lukehb** [comment]
Okay thank you. We are now looking into breaks in shipping bug, it is reproducible on our side too.

**Comment by lukehb** [comment]
I have confirmed AWS G4dn, with a T4, works without any additional installation of drivers when I use the Ubuntu Deep Learning AMI. https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-AWS-Deep-Learning-AMI-Ubuntu-1/B07Y43P7X5
