### ISSUE TITLE
Supported Browsers

### ISSUE THREAD

**Issue by jgiovino** [adamrehn/pixel-streaming-linux#38]
Please help me determine the best way to configure a browser to support this WebRTC server.

I am running the Epic PixelStreamingDemo copied from windows Epic launcher and compiled with your 4.25 UE4.
Thank you for all of this tremendous work.
The following observations are from running the servers on a Centos7 distro.

The demo works great on my LGTV browser, Safari 14.0.2,  Opera, and on Chrome 88.0 (Win and Linux).

I have not been able to run the demo in any other browser.
I failed to run in Brave, Firefox, MS Edge, InternetExplorer and the latest version of Chrome (89.0)

Please help me determine the best way to configure a browser to support this WebRTC server.

Chrome (89.0)
after 'click to start'
[2021.03.09-17.48.27:433][ 96]LogPixelStreamingSS: Error: Failed to parse answer's SDP
...
Failed to find symbol file, expected location:
".../LinuxNoEditor/PixelStreamingDemo/Binaries/Linux/PixelStreamingDemo.sym"

Brave (1.21.74 Chromium 89.0.4389.72):
after 'click to start' 
[2021.03.09-17.22.28:329][721]LogPixelStreamingSS: Error: Failed to parse answer's SDP

MS Edge: 
'click to start' does not register
but works when run without PixelDemo.htm

Firefox:
cant handle css formatting;
but works without specifying PixelDemo.htm

**Comment by lukehb** [comment]
There is a reported bug in Chrome 89, and by extension all browsers based on it, where it sends an SDP offer that UE's WebRTC cannot handle. Until we upgrade WebRTC the fix for those Chrome versions is:

Add this line `webRtcPlayer.js` to webRTCPlayer() constructor, roughly line 65.

`this.cfg.offerExtmapAllowMixed = false`

We will be testing this and pushing a change shortly.

For Edge and FF, where the page is broken due html/css/js, we have recently pushed some changes to the PixelDemo's html/css/js to fix this, so please use our fixed files in SignalingWebServer, **not PixelDemo.htm that ships with the Pixel Streaming demo**. See here: https://github.com/ImmortalEmperor/UnrealEngine/blob/4.25-pixelstreaming/Engine/Source/Programs/PixelStreaming/WebServers/SignallingWebServer/

**As always, IE is not support and can go play in traffic.**
