### ISSUE TITLE
some basic question for pixel streaming in linux

### ISSUE THREAD

**Issue by comsyspro** [adamrehn/pixel-streaming-linux#39]
i want to know if it is also possible to run pixel streaming on a local linux installation or do you need this unreal container solution for this?

i tried following:
on ubuntu 20.04 desktop i installed ue4 opened the "first person template", enabled the pixel streaming plugin and packaged this project (in shipping mode). after that i started the cirrus.js with http port 80 and streaming port 8888. then i started the project with the flags firstpersontempl.sh -RenderOffScreen -PixelStreamingIP=localhost -PixelStreamingPort=8888. the problem is that there is no stream on port 8888, normally the cirrus server should receive here the stream but nothing happens.

so i ask me now if this is not possible on a local linux installation and you need your container solution for this to work? if yes where can i find a step by step tutorial so i know which commands i have to run (at the moment i have no overview about using dockerfile etc. and i don't understand your concept).

thank you.

**Comment by adamrehn** [comment]
Yes, Pixel Streaming for Linux will work just fine outside of a container. It is very likely that you are simply encountering the bug that causes things to break in Shipping configuration (https://github.com/adamrehn/pixel-streaming-linux/issues/37) and re-packaging your project in Development configuration will cause everything to start working as expected.

There are step-by-step instructions available in the [Building and running](https://github.com/ImmortalEmperor/UnrealEngine/tree/4.25-pixelstreaming#building-and-running) section of the README for the 4.25 version of Pixel Streaming for Linux. You will need to make sure that you are using the correct fork of the Unreal Engine as described in the README, since the upstream version of the Unreal Engine does not contain our changes to make Pixel Streaming work under Linux.

**Comment by comsyspro** [comment]
thank you for your answer. i didn't know it that you need a special ue4 version for this, so i would then try to use this version now `git clone --depth 1 https://github.com/ImmortalEmperor/UnrealEngine.git -b 4.25-pixelstreaming`.
