### ISSUE TITLE
Running Pixel Stream, in "Play Mode"

### ISSUE THREAD

**Issue by Schizo** [adamrehn/pixel-streaming-linux#9]
This might be off-topic, but would it be possible to run the pixel-stream without building it just by launching the ue4editor?

**Comment by adamrehn** [comment]
According to the [Getting Started with Pixel Streaming](https://docs.unrealengine.com/en-US/Platforms/PixelStreaming/PixelStreamingIntro/index.html) page of the official Pixel Streaming documentation, streaming can be used either in packaged projects or when running the project from the Editor in "standalone game" mode, which can be triggered like so:

```bash
# Replace "/path/to/Engine" with the path to your Unreal Engine installation
# Replace "/path/to/project.uproject" with the path to your Unreal project file
/path/to/Engine/Binaries/Linux/UE4Editor "/path/to/project.uproject" -game
```

And yes, this question is indeed off-topic, since it is not specific to the Linux version of Pixel Streaming. General questions about using the Pixel Streaming system should be posted in the appropriate venue, such as the [Unreal Engine forums](https://forums.unrealengine.com/) or [AnswerHub](https://answers.unrealengine.com/).
